---
title: "projet"
output: html_document
date: "2024-04-09"
---


1) ACM

```{r}
rm(list=ls())
sante_mentale=read.csv("sante_mentale_regrouped.csv")
sante_mentale
```

# 1, analyse d'une sous partie
# Sous partie

```{r}
library(dplyr)
# Permet de créer une sous base de donnée avec juste les variables qu'on veut
 sub_database <- sante_mentale %>% 
   dplyr::select(diagnostic_episode_depressif, sport,niveau_etude, depressif,anxiété)
 

```


As_factors of all variables
```{r}
# Transforme tout ce qui est en caractère en asfactor
sub_database[] <- lapply(sub_database, function(x) if(is.character(x)) factor(x) else x)
sub_database$age <- factor(sub_database$age)
sub_database
```

# Analyse ACM
On a toutes les conditions nécessaires au bon fonctionnement de l'ACM maintenant
```{r}
library(FactoMineR)
# Perform MCA on the sub-database
mca_results <- MCA(sub_database, graph = FALSE)
# Afficher la variance expliquée par chaque dimension
print(mca_results$eig)
```


```{r}
# If you have the factoextra package installed, you can visualize the results:
library(factoextra)

# Visualiser le cercle de corrélation des variables pour les deux premières dimensions
fviz_mca_var(mca_results, choice = "mca.cor", axes = c(1, 2), repel = TRUE)
fviz_mca_var(mca_results, choice = "mca.cor", axes = c(2, 3), repel = TRUE)
fviz_mca_var(mca_results, choice = "mca.cor", axes = c(4, 5), repel = TRUE)
fviz_mca_var(mca_results, choice = "mca.cor", axes = c(1,5), repel = TRUE)

plot_mca = plot.MCA(mca_results, invisible=c("ind"), hab="quali", palette=palette(c("blue","orange","darkgreen")),repel = TRUE) +
              theme_minimal(base_size = 20) +  # Increase base text size
  theme(axis.text.x = element_text(size = 18), 
        axis.text.y = element_text(size = 18),
        plot.title = element_text(size = 24),
        plot.background = element_rect(fill = "white", color = NA), # Ensure white background
        panel.background = element_rect(fill = "white", color = NA)) # Ensure panel background is white

# Enregistrer l'image
ggsave("mca_factor_map_large.png",plot = plot_mca, width = 24, height = 16, dpi = 300)

print(plot_mca)
```
```{r}
# Scree plot to visualize the variance explained by each dimension
fviz_screeplot(mca_results, addlabels = TRUE, ylim = c(0, 50))

```





