---
title: "Classification_supervisée"
output: html_notebook
---

```{r}
sub_sante_mentale=read.csv("sub_sante_mentale.csv",sep=",")
sub_sante_mentale <- sub_sante_mentale[sub_sante_mentale$depressif %in% c("Oui", "Non"), ]

# Convertir toutes les variables du dataframe en facteurs
for (column in names(sub_sante_mentale)) {
  sub_sante_mentale[[column]] <- as.factor(sub_sante_mentale[[column]])
}

# Subsetting the dataframe to keep only rows where depressif is "Oui" or "Non"
sub_sante_mentale
```


Permet de regrouper les Bac +1, +2 et +3, et un autre groupe avec +4, +5
```{r}
# Permet de regrouperpar Licence (Bac +1-3) et Master (Bac +4-5) et le reste, comme ça on a moins de catégorie derrière, ça va aider pour l'acm, l'acf etc 
sub_sante_mentale$niveau_etude <- as.factor(sapply(sub_sante_mentale$niveau_etude, function(x) {
  if (x %in% c("Bac +1", "Bac +2", "Bac +3")) {
    "BAC+1-3"
  } else if (x %in% c("Bac +4", "Bac +5")) {
    "BAC+4-5"
  } else {
    x  # This line ensures that all other levels remain unchanged
  }
}))
```


Permet de regrouper les différents pays d'étude
```{r}
# C'est la fréquence max qu'on accepte avant de garder comme une catégorie
threshold <- 5  # Set a threshold for the minimum frequency

# Permet d'avoir la fréquence de différente catégorie de chaque variable de la subdatabase
level_frequencies <- table(sub_sante_mentale$ville_foyer)

# Permet d'avoir les différentes villes qui sont endessous de la fréquence qu'on a mis
rare_levels <- names(level_frequencies[level_frequencies < threshold])

# Puis remplace chaque ville qui sont dans la liste rare_levels par other dansla subdatabase
sub_sante_mentale$ville_foyer <- as.factor(sapply(sub_sante_mentale$ville_foyer, function(level) {
  if (level %in% rare_levels) "Other" else level
}))
```




```{r}
# Préparation des données
set.seed(1) # Permet de pouvoir reproduire les mêmes résultats
n <- nrow(sub_sante_mentale) 
test.ratio <- 0.2 # Le taux de la db qu'on va utilisé comme test
n.test <- round(n * test.ratio) # Permet de savoir le nombre d'observation pour les test
tr <- sample(1:n, n.test)  
sub_sante_mentale.test <- sub_sante_mentale[tr, ] 
sub_sante_mentale.train <- sub_sante_mentale[-tr, ]

```

```{r}

# Examiner les valeurs uniques par groupe de 'depressif'
aggregate(sub_sante_mentale[], by=list(sub_sante_mentale$depressif), function(x) length(unique(x)))


```


# LDA
```{r}
res_lda <- lda(sub_sante_mentale$depressif~., data=sub_sante_mentale.train)
pred_lda <- predict(res_lda, newdata=sub_sante_mentale.test)$class
table_lda <- table(Predicted=pred_lda, Actual=sub_sante_mentale.test$depressif)
accuracy_lda <- sum(diag(table_lda)) / n.test
```


LDA
```{r}
library(MASS)
# LDA
res_lda <- lda(sub_sante_mentale$depressif ~ ., data =sub_sante_mentale)
summary(res_lda)
```

Prédiction
```{r}
pred_lda_classe = predict(res_lda, newdata=sub_sante_mentale.test)$class
print(pred_lda_classe)
```


Accuracy
```{r}
confusion_table_lda <- table(Prédiction = pred_lda_classe, Réalité = sub_sante_mentale.test$depressif)
print(confusion_table_lda)

print(sum(diag(confusion_table_lda))/n.test)

accuracy_lda = mean(pred_lda_classe == sub_sante_mentale.test$DIFF)
print(accuracy_lda)
```



Proba
```{r}
#proba a posteriori de succes (dans la deuxième colonne) : 
pred_lda <- predict(res_lda,newdata=sub_sante_mentale.test)$posterior[,2] 

ROC_lda <- roc(sub_sante_mentale.test$depressif, pred_lda)
plot(ROC_lda, print.auc=TRUE,  print.auc.y = 0.5)
ROC_lda$auc
```



```{r}
# Courbe ROC pour LDA
library(pROC)
pred_lda_prob <- predict(res_lda, newdata=sub_sante_mentale.test)$posterior[,2]
ROC_lda <- roc(sub_sante_mentale.test$depressif, pred_lda_prob)
plot(ROC_lda, print.auc=TRUE)
```


# CART

```{r}
library(rpart)
arbre.opt <- rpart(depressif~., data=sub_sante_mentale.train)
pred_cart <- predict(arbre.opt, sub_sante_mentale.test, type="class")
table_cart <- table(Predicted=pred_cart, Actual=sub_sante_mentale.test$depressif)
accuracy_cart <- sum(diag(table_cart)) / n.test

# Courbe ROC pour CART
pred_cart_prob <- predict(arbre.opt, sub_sante_mentale.test, type="prob")[,2]
ROC_cart <- roc(sub_sante_mentale.test$depressif, pred_cart_prob)
plot(ROC_cart, print.auc=TRUE)
```



# Random Forest

```{r}
library(randomForest)
fit_RF <- randomForest(depressif~., data=sub_sante_mentale.train)
pred_RF <- predict(fit_RF, sub_sante_mentale.test, type="class")
table_RF <- table(Predicted=pred_RF, Actual=sub_sante_mentale.test$depressif)
accuracy_RF <- sum(diag(table_RF)) / n.test

# Courbe ROC pour Random Forest
pred_RF_prob <- predict(fit_RF, sub_sante_mentale.test, type="prob")[,2]
ROC_RF <- roc(sub_sante_mentale.test$depressif, pred_RF_prob)
plot(ROC_RF, print.auc=TRUE)
```


# Comparaison des modèles
```{r}
results <- rbind(
  lda=c(Accuracy=accuracy_lda, AUC=as.numeric(ROC_lda$auc)),
  cart=c(Accuracy=accuracy_cart, AUC=as.numeric(ROC_cart$auc)),
  rf=c(Accuracy=accuracy_RF, AUC=as.numeric(ROC_RF$auc))
)
results

# Afficher les résultats et identifier le meilleur modèle
best_model <- apply(results, 2, which.max)
best_model
```

